### ISSUE TITLE
Root node does not work when set to document.body

### ISSUE THREAD

**Issue by KevinGrandon** [gaia-components/gaia-dom-tree#1]
I think we get into an infinite loop somewhere.

**Comment by justindarc** [comment]
@KevinGrandon That's the default demo. Its using the entire DOM instead of referencing a specific element. If you set a different root, it works.

**Comment by KevinGrandon** [comment]
Hmm, I tried setting this to document.body and it seemed to not work. What should it be set to?

**Comment by justindarc** [comment]
Try:

```
var root = document.getElementById('root');
```

**Comment by KevinGrandon** [comment]
I want to use this on a page which does not have a #root element though. I want to use document.body and not root :)

**Comment by justindarc** [comment]
Hmm.. Yeah.. I can see that might be a problem :-)

I thought you were just trying to run the demo.

We'll need to put a stop condition when traversing the DOM. Let's keep this open until we land a fix.

**Comment by KevinGrandon** [comment]
Possibly we're injecting content into the page for the addon, and MutationObserver is seeing that content?

**Comment by justindarc** [comment]
I think so. We need to stop the component from seeing itself and traversing into its shadow DOM.
